### PR TITLE
fix: made inventory UI read only

### LINKED ISSUE #315: Inventory read-only UI system

### PR DESCRIPTION
**Pull request by callmekungfu**
### Related Issue(s)

resolves #315

### Quick overview of the change

CleanShot 2022-10-24 at 11 43 41@2x

Made buttons read only

### CODE REVIEW

File: client/src/pages/inventory/ProductBase.tsx [hunk 1]
```diff
@@ -99,6 +101,9 @@ const ProductBase: React.FC<ProductBaseProps> = ({
           hover
           sx={{ cursor: 'pointer' }}
           onClick={() => {
+            if (!canWrite) {
```
Comment (Wuon) [inline client/src/pages/inventory/ProductBase.tsx:104]: guessing there wasn't a disabled prop :(

**Review by Wuon — APPROVED** [review]

File: client/src/pages/inventory/ProductBase.tsx (hunk 1 above)
Comment (Wuon) [reply client/src/pages/inventory/ProductBase.tsx:104]: yea just checked, there isn't one :(((
