### PR TITLE
fix(#224): redirect user to login when token expires

### LINKED ISSUE #224: The app does not automatically log the user out if their session is expired

### PR DESCRIPTION
**Pull request by Wuon**
resolves #224 

https://user-images.githubusercontent.com/20260270/191639421-8c93810b-2f8c-439f-9983-e57b36431c8a.mov

Screen Shot 2022-09-21 at 9 13 27 PM

### CODE REVIEW

File: client/src/data/auth.ts [hunk 1]
```diff
@@ -20,7 +20,7 @@ export const login = async (data: AuthBody): Promise<UserNoAccessToken> => {
     .then((res) => res.data);
   // Set data in localStorage
   set(ACCESS_TOKEN_KEY, accessToken);
-  set(ACCESS_TOKEN_EXPIRY_KEY, `${getExpiryOfJwt(accessToken)}`);
+  set(ACCESS_TOKEN_EXPIRY_KEY, `${getExpiryOfJwt(accessToken)}000`);
```
Comment (callmekungfu) [inline client/src/data/auth.ts:23]: why are the `000` needed

**Review by callmekungfu — COMMENTED** [review]
Quick question, please add comments regarding it

File: client/src/data/auth.ts (hunk 1 above)
Comment (Wuon) [reply client/src/data/auth.ts:23]: will add comment, but its because js Date object is in milliseconds, whereas jwt date is in seconds.

the bug was because when we transform the jwt expiry into a date obj, it'll like never hit the condition to logout

Comment (callmekungfu) [reply client/src/data/auth.ts:24]: I think we should use `date-fns`'s `parseJSON` to parse the JSON date string instead of manually adding the three 0s and use date-fns to perform the comparison

What do you think?

File: client/src/pages/login/index.tsx [hunk 2]
```diff
@@ -40,6 +40,10 @@ function LoginPage() {
     if (checkIsLoggedIn()) {
       goToHome();
     }
+
+    if (checkIsExpired()) {
+      setError('Your session has expired. Please login again to continue.');
```
Comment (callmekungfu) [inline client/src/pages/login/index.tsx:45]: Are we removing the expired token from storage as well?

Comment (Wuon) [reply client/src/pages/login/index.tsx:45]: Yea let me add that in, makes sense since we prompt the message

File: client/src/data/auth.ts (hunk 1 above)
Comment (Wuon) [reply client/src/data/auth.ts:24]: oh cool didn't know about that. leaving this here for posterity

https://github.com/date-fns/date-fns/blob/main/src/parseJSON/index.ts

Comment (Wuon) [reply client/src/data/auth.ts:24]: ok nevermind I looked into it and it won't work.

If you want it to be more explicit in naming the closest thing is this:

```
fromUnixTime(+getExpiryOfJwt(accessToken)).getTime().toString()
```

but at that point I would would rather have the original:
```
`${getExpiryOfJwt(accessToken)}000`);
```

lmk which one you prefer. I personally want to stick with the original one.

Comment (callmekungfu) [reply client/src/data/auth.ts:24]: Just leave the comment referencing this discussion and we should be gtg

**Review by callmekungfu — APPROVED** [review]
